/*
 * madana-api
 *
 * <h1>Using the madana-api</h1>        <p>This documentation contains a Quickstart Guide, relating client functionality and information about the available         endpoints and used datamodels.   </p>       <p> The madana-api and its implementations are still in heavy development. This means that there may be problems in our protocols, or there may be mistakes in our implementations. We take security vulnerabilities very seriously. If you discover a security issue, please bring it to our attention right away! If you find a vulnerability that may affect live deployments -- for example, by exposing a remote execution exploit -- please send your report privately to info@madana.io. Please DO NOT file a public issue. If the issue is a protocol weakness that cannot be immediately exploited or something not yet deployed, just discuss it openly   </p>   <br>   <p> Note: Not all functionality might be acessible without having accquired and api-license token. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a> </p>       <br>
 *
 * API version: 0.5.0-master.48
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package madanaapiclient

import (
	"encoding/json"
)

// XmlNs0WireguardInterfaceAllOf struct for XmlNs0WireguardInterfaceAllOf
type XmlNs0WireguardInterfaceAllOf struct {
	// 
	Port *string `json:"port,omitempty"`
}

// NewXmlNs0WireguardInterfaceAllOf instantiates a new XmlNs0WireguardInterfaceAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewXmlNs0WireguardInterfaceAllOf() *XmlNs0WireguardInterfaceAllOf {
	this := XmlNs0WireguardInterfaceAllOf{}
	return &this
}

// NewXmlNs0WireguardInterfaceAllOfWithDefaults instantiates a new XmlNs0WireguardInterfaceAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewXmlNs0WireguardInterfaceAllOfWithDefaults() *XmlNs0WireguardInterfaceAllOf {
	this := XmlNs0WireguardInterfaceAllOf{}
	return &this
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *XmlNs0WireguardInterfaceAllOf) GetPort() string {
	if o == nil || o.Port == nil {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *XmlNs0WireguardInterfaceAllOf) GetPortOk() (*string, bool) {
	if o == nil || o.Port == nil {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *XmlNs0WireguardInterfaceAllOf) HasPort() bool {
	if o != nil && o.Port != nil {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *XmlNs0WireguardInterfaceAllOf) SetPort(v string) {
	o.Port = &v
}

func (o XmlNs0WireguardInterfaceAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Port != nil {
		toSerialize["port"] = o.Port
	}
	return json.Marshal(toSerialize)
}

type NullableXmlNs0WireguardInterfaceAllOf struct {
	value *XmlNs0WireguardInterfaceAllOf
	isSet bool
}

func (v NullableXmlNs0WireguardInterfaceAllOf) Get() *XmlNs0WireguardInterfaceAllOf {
	return v.value
}

func (v *NullableXmlNs0WireguardInterfaceAllOf) Set(val *XmlNs0WireguardInterfaceAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableXmlNs0WireguardInterfaceAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableXmlNs0WireguardInterfaceAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableXmlNs0WireguardInterfaceAllOf(val *XmlNs0WireguardInterfaceAllOf) *NullableXmlNs0WireguardInterfaceAllOf {
	return &NullableXmlNs0WireguardInterfaceAllOf{value: val, isSet: true}
}

func (v NullableXmlNs0WireguardInterfaceAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableXmlNs0WireguardInterfaceAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


